WEBITOOLS-106: When none provided, assigned a default exclusion rules and patterns
CAST-Extend/com.castsoftware.aip.console.tools pull request #100
Opened 2022-05-16 14:27 UTC by leon2Meudon92

…and exclusion patterns as well

2022-05-23 07:53 UTC, leon2Meudon92 commented on aip-console-tools-cli/README.md
> +  *example* `--rules` = "EXCLUDE_EMPTY_PROJECTS,PREFER_FULL_DOT_NET_TO_BASIC_DOT_NET_WEB,EXCLUDE_TEST_CODE"
They are listed on command -help
Let me add this comment to help finding the list in case of

2022-05-23 15:29 UTC, Krelix requested changes
A few changes to be added

2022-05-23 15:33 UTC, leon2Meudon92 commented on aip-console-tools-cli/src/main/java/com/castsoftware/aip/console/tools/commands/DeliverVersionCommand.java
> +    @CommandLine.Option(names = {"-rules", "--exclusion-rules"}, split = ",", type = ExclusionRuleType.class
updating

2022-05-23 15:36 UTC, leon2Meudon92 commented on aip-console-tools-cli/src/main/java/com/castsoftware/aip/console/tools/commands/DeliverVersionCommand.java
> +                exclusions.setExclusionRules(Arrays.asList(exclusionRules).stream().collect(Collectors.toSet()));
Set doesn't work. I tested it and still looking for a bean Set.

2022-05-23 15:38 UTC, leon2Meudon92 commented on aip-console-tools-core/src/main/java/com/castsoftware/aip/console/tools/core/dto/Exclusions.java
> +        return Arrays.asList("tmp/", "temp/", "*test", "tests", "target/", ".svn/", ".git/", "_Macosx/").stream().collect(Collectors.toSet());
It's the way Console handle that pattern. I couldn't change it like that

2022-05-24 08:51 UTC, Krelix commented on aip-console-tools-cli/src/main/java/com/castsoftware/aip/console/tools/commands/DeliverVersionCommand.java
> +                exclusions.setExclusionRules(Arrays.asList(exclusionRules).stream().collect(Collectors.toSet()));
You didn't read my whole comment :)

Please replace Arrays.asList()... with the following (if it doesn't work, we can discuss this directly) :
```suggestion
                exclusions.setExclusionRules(Arrays.stream(exclusionRules).collect(Collectors.toSet()));
```

2022-05-24 13:08 UTC, Krelix approved these changes

2022-05-24 13:09 UTC, merged