WEBITOOLS-224: Adds option to include fast scan in deep analysis job
CAST-Extend/com.castsoftware.aip.console.tools pull request #187
Opened 2024-02-14 09:00 UTC by CAST-ANJ

2024-02-15 08:58 UTC, leon2Meudon92 commented
You already have a command that does that

2024-02-15 09:44 UTC, CAST-ANJ commented
This is different from that. It is related to the new feature added in the console to include fast scan in deep analysis job It modifies the command to align with the new params of api -> /deep-analysis

2024-02-15 10:39 UTC, leon2Meudon92 commented
They are comments reviews

2024-02-15 11:16 UTC, leon2Meudon92 requested changes

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +        String expandedSourcePath = vars.expand(sourcePath);
environmentVariables.expand(x) does that

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +        String expandedIncludeFastScan = vars.expand(environmentVariables.get("INCLUDE_FAST_SCAN"));
environmentVariables can also expand

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +                _sourcePath = uploadService.uploadFileForOnboarding(Paths.get(expandedSourcePath).toFile(), existingAppGuid);
upload only if ANALYZED
If source path is empty what you do
@NotNull constraint should be added

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +                    logger.println("Application should be analyzed to include fast scan in deep analysis. Deep analysis will continue without fast scan");
add message resource instead

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +                    , Boolean.valueOf(expandedIncludeFastScan), _sourcePath, jnksLogPollingProvider);
Boolean.valueOf(expandedIncludeFastScan) should have been converted earlier
boolean b = Boolean.valueOf(expandedIncludeFastScan)
and use b everywhere

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-jenkins/src/test/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilderTest.java
> +        expectedResults.setSourcePath("");
Add another test with non empty path

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-tools-cli/src/main/java/com/castsoftware/aip/console/tools/commands/OnboardApplicationDeepAnalysisCommand.java
> +            + " if specified without parameter: ${FALLBACK-VALUE}", fallbackValue = "false")
fallback should be true

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-tools-core/src/main/java/com/castsoftware/aip/console/tools/core/services/ApplicationServiceImpl.java
> +                sourcePath = uploadService.uploadFileAndGetSourcePath(app.getName(), app.getGuid(), properties.getSourcePath());
Only perform the upload when required: status==ANALYZED

2024-02-15 11:16 UTC, leon2Meudon92 commented on aip-console-tools-core/src/main/java/com/castsoftware/aip/console/tools/core/services/ApplicationServiceImpl.java
> +            throw new RuntimeException(e);
give a precise error code

2024-02-15 11:56 UTC, CAST-ANJ commented on aip-console-tools-cli/src/main/java/com/castsoftware/aip/console/tools/commands/OnboardApplicationDeepAnalysisCommand.java
> +            + " if specified without parameter: ${FALLBACK-VALUE}", fallbackValue = "false")
fallback is false on console side.

2024-02-15 12:35 UTC, leon2Meudon92 commented
Please don't forget to add a new JENKINS CLI job like the one a showed above

2024-02-16 07:07 UTC, CAST-ANJ commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +                _sourcePath = uploadService.uploadFileForOnboarding(Paths.get(expandedSourcePath).toFile(), existingAppGuid);
Changes done

2024-02-16 07:08 UTC, CAST-ANJ commented on aip-console-jenkins/src/test/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilderTest.java
> +        expectedResults.setSourcePath("");
Changes done

2024-02-16 07:11 UTC, CAST-ANJ commented on aip-console-tools-core/src/main/java/com/castsoftware/aip/console/tools/core/services/ApplicationServiceImpl.java
> +                sourcePath = uploadService.uploadFileAndGetSourcePath(app.getName(), app.getGuid(), properties.getSourcePath());
Changes done

2024-02-16 07:11 UTC, CAST-ANJ commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +        String expandedSourcePath = vars.expand(sourcePath);
Changes done

2024-02-16 07:11 UTC, CAST-ANJ commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +                    logger.println("Application should be analyzed to include fast scan in deep analysis. Deep analysis will continue without fast scan");
Changes done

2024-02-16 07:11 UTC, CAST-ANJ commented on aip-console-tools-core/src/main/java/com/castsoftware/aip/console/tools/core/services/ApplicationServiceImpl.java
> +            throw new RuntimeException(e);
Changes done

2024-02-16 07:11 UTC, CAST-ANJ commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +                    , Boolean.valueOf(expandedIncludeFastScan), _sourcePath, jnksLogPollingProvider);
Changes done

2024-02-16 07:12 UTC, CAST-ANJ commented on aip-console-jenkins/src/main/java/io/jenkins/plugins/aipconsole/OnboardApplicationDeepAnalysisBuilder.java
> +        String expandedIncludeFastScan = vars.expand(environmentVariables.get("INCLUDE_FAST_SCAN"));
Changes done

2024-02-16 14:43 UTC, merged